### ISSUE TITLE
Festival backend ignores apostrophes

### ISSUE THREAD

**Issue by yvt** [bootphon/phonemizer#12] opened 2018-08-21 07:10 UTC
```
$ echo "I'm looking for a job as a digital assistant." | phonemize
ihm luhkaxng faor ax jhaab aez ax dihjhaxtaxl axsihstaxnt

$ echo "Im looking for a job as a digital assistant." | phonemize
ihm luhkaxng faor ax jhaab aez ax dihjhaxtaxl axsihstaxnt
```

**Comment by mmmaat** [comment] 2018-08-27 09:48
Hi,

This is not a bug but the expected behavior. The apostrophe is not displayed but pronounced... For example:

https://github.com/bootphon/phonemizer/blob/c41e5e10c35f1ce8279565f2f380dd66a59a288a/test/test_festival.py#L43-L47

**Comment by mmmaat** [comment] 2018-08-28 08:31
Ok thank you for pointing out that bug, because it is a bug I recently introduced... In a former version we had:
```
$ echo "I'm looking for an image." | phonemize
aym luhkaxng faor axn ihmaxjh
$ echo "Im looking for an image." | phonemize
ihm luhkaxng faor axn ihmaxjh 
```

In the latest release we have:

```
$ echo "I'm looking for an image." | phonemize
ihm luhkaxng faor axn ihmaxjh
$ echo "Im looking for an image." | phonemize
ihm luhkaxng faor axn ihmaxjh 
```

I will correct that very soon. Note that the bug concerns only the *festival* backend, you can still use the *espeak* one:

```
$ echo "I'm looking for an image." | phonemize -l en-gb
aɪm lʊkɪŋ fəɹən ɪmɪdʒ
$ echo "Im looking for an image." | phonemize -l en-gb
ɪm lʊkɪŋ fəɹən ɪmɪdʒ
```

**Comment by mmmaat** [comment] 2018-08-28 14:54
Fixed in commit https://github.com/bootphon/phonemizer/commit/a2af4801aafb2c0032b955701865d168379462b1

**Closed by mmmaat** 2018-08-28 14:54 UTC
Labels: bug
